name: simple_date
description: A simple date model for Dart.
version: 1.0.0
homepage: https://github.com/jeroen-meijer/simple_date
repository: https://github.com/jeroen-meijer/simple_date

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: 1.7.0

dev_dependencies:
  coverage: 1.0.3
  test: 1.17.10
  very_good_analysis: 2.3.0
