name: simple_date
description: A simple date model for Dart with no notion of time. Useful for
  applications that rely on date-only events such as birthdays, anniversaries,
  and date ranges.
version: 1.1.0
homepage: https://github.com/jeroen-meijer/simple_date
repository: https://github.com/jeroen-meijer/simple_date

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  checks: ^0.2.2
  coverage: ^1.6.3
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1
